apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-stjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-stjp
    app.kubernetes.io/part-of: my-app-2
  name: devfile-sample-java-springboot-basic-stjp
spec:
  rules:
  - host: devfile-sample-java-springboot-basic-stjp-pshivpuj-tenant.$121.ip.io
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-java-springboot-basic-stjp
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
